<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<!-- Disable compression (optional, based on use case) -->
		<CompressionEnabled>false</CompressionEnabled>
		<!-- Disables the Hot Reload background client for WASM -->
		<WasmEnableHotReload>false</WasmEnableHotReload>
	</PropertyGroup>

	<ItemGroup>
		<!-- Add Blazor support to SpawnJS -->
		<PackageReference Include="SpawnDev.SpawnJS.Blazor" Version="2.1.7" />
		
		<PackageReference Include="SpawnDev.SpawnJS.RazorRenderer" Version="2.1.0" />

		<!-- Required in the exe project (this one) -->
		<PackageReference Include="SpawnDev.SpawnJS.WebWorkers" Version="2.1.2" />


		<ProjectReference Include="..\SpawnDev.AI.Server\SpawnDev.AI.Server.csproj" />
	</ItemGroup>

</Project>
